apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-result-deploy
  labels:
    name: voting-result-app-pod
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-result-app-pod
      app: demo-voting-app
  template:
    metadata:
      name: voting-result-app-pod
      labels:
        name: voting-result-app-pod
        app: demo-voting-app
    spec:
      containers:
        - name: voting-result-app
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80
    